# Generated by Django 4.2.5 on 2023-09-19 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='pais',
            field=models.ForeignKey(default='AR', on_delete=django.db.models.deletion.CASCADE, to='api.pais'),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.CharField(max_length=200),
        ),
    ]
