# Generated by Django 4.2.5 on 2023-09-22 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_ciudad_remove_hotel_pais_provincia_direccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='id',
        ),
        migrations.AlterField(
            model_name='ciudad',
            name='codigo_postal',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
