# Generated by Django 4.2.5 on 2023-09-22 00:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_ciudad_id_alter_ciudad_codigo_postal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.direccion'),
        ),
    ]
