# Generated by Django 4.2.5 on 2023-09-22 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_hotel_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('documento', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
            ],
            bases=('api.persona',),
        ),
        migrations.CreateModel(
            name='Encargado',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.persona')),
                ('hotel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.hotel')),
            ],
            bases=('api.persona',),
        ),
    ]
