# Generated by Django 4.2.5 on 2023-09-28 02:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_alter_hotel_direccion'),
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='hotel',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel'),
        ),
    ]
