# Generated by Django 4.2.5 on 2023-09-28 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ubicacion', '0001_initial'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='direccion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ubicacion.direccion'),
        ),
    ]
