# Generated by Django 4.2.5 on 2023-10-16 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipohabitacion'),
        ('hotel', '0002_remove_habitacion_tipo_hotel_tipos_de_habitacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion'),
        ),
    ]
