# Generated by Django 4.2.5 on 2023-11-19 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_remove_hotel_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='paquete',
        ),
        migrations.AddField(
            model_name='paquetepromocional',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='paquetepromocional',
            name='habitaciones',
            field=models.ManyToManyField(to='hotel.habitacion'),
        ),
    ]
