# Generated by Django 4.2.5 on 2023-10-20 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tipohabitacion_precio'),
        ('hotel', '0004_hotel_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habitacion',
            name='precio',
        ),
        migrations.AddField(
            model_name='hotel',
            name='encargado',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.encargado'),
        ),
        migrations.CreateModel(
            name='PrecioPorTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('tipohabitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='HotelVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.hotel')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendedor')),
            ],
        ),
    ]
