# Generated by Django 4.2.5 on 2023-10-22 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encargado_encargado_asignado'),
        ('hotel', '0007_alter_hotel_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
