# Generated by Django 4.2.5 on 2023-11-04 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquetepromocional',
            name='habitaciones',
            field=models.ManyToManyField(to='hotel.habitacion'),
        ),
    ]
