# Generated by Django 4.2.5 on 2023-11-04 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_paquetepromocional_habitaciones'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paquetepromocional',
            name='habitaciones',
        ),
    ]
