# Generated by Django 4.2.5 on 2023-11-04 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_remove_paquetepromocional_habitaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='paquete',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='hotel.paquetepromocional'),
        ),
    ]
