# Generated by Django 4.2.5 on 2023-11-04 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0014_habitacion_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='paquete',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.paquetepromocional'),
        ),
    ]
