# Generated by Django 4.2.5 on 2023-11-04 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_puntos'),
        ('hotel', '0015_alter_habitacion_paquete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='paquete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotel.paquetepromocional'),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='tipo_habitacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion'),
        ),
    ]
