# Generated by Django 4.2.5 on 2023-11-06 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0019_temporada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporada',
            name='tipo',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Alta'), (1, 'Baja')]),
        ),
    ]
