# Generated by Django 4.2.5 on 2023-11-10 18:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0020_alter_temporada_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioportipo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator('0.01')]),
        ),
    ]
