# Generated by Django 4.2.5 on 2023-11-10 19:17

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0021_alter_precioportipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioportipo',
            name='precio',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
