# Generated by Django 4.2.5 on 2023-11-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0022_alter_precioportipo_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='numero_de_habitacion',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='habitacion',
            name='piso',
            field=models.PositiveIntegerField(),
        ),
    ]
