# Generated by Django 4.2.5 on 2023-11-10 19:34

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0023_alter_habitacion_numero_de_habitacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquetepromocional',
            name='coeficiente_descuento',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))]),
        ),
    ]
