# Generated by Django 4.2.5 on 2023-11-11 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0024_alter_paquetepromocional_coeficiente_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='./fixtures/img/hoteles'),
        ),
    ]
