# Generated by Django 4.2.5 on 2023-11-11 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0025_hotel_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
