# Generated by Django 4.2.5 on 2023-11-03 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_puntos'),
        ('hotel', '0011_descuento'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=80)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('numero', models.IntegerField()),
                ('tipo_factura', models.CharField(max_length=1)),
                ('importe_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField()),
                ('tipo_pago', models.PositiveSmallIntegerField(choices=[(0, 'CONTADO'), (1, 'PUNTOS'), (2, 'TARJETA')])),
            ],
        ),
        migrations.AddField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cliente'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='habitaciones',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.habitacion'),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='importe',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='alquiler',
            name='paquetes',
            field=models.ManyToManyField(blank=True, null=True, to='hotel.paquetepromocional'),
        ),
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('fecha_emision', models.DateField()),
                ('fecha_pago', models.DateField(null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.detalle_factura')),
            ],
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='alquiler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.alquiler'),
        ),
        migrations.AddField(
            model_name='detalle_factura',
            name='factura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.factura'),
        ),
    ]
