# Generated by Django 4.2.5 on 2023-12-01 00:04

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alquiler',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.expressions.Case, to='core.vendedor'),
        ),
    ]
