# Generated by Django 4.2.5 on 2023-12-01 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_direccion'),
        ('venta', '0002_alquiler_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='core.cliente'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alquileres', to='core.vendedor'),
        ),
    ]
