# Generated by Django 4.2.5 on 2023-11-04 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_detalle_factura_factura_pago_alquiler_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liquidacion',
            name='detalle_factura',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='venta.detalle_factura'),
        ),
    ]
