# Generated by Django 4.2.5 on 2023-11-04 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_descuento'),
        ('venta', '0003_alter_liquidacion_detalle_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='habitaciones',
            field=models.ManyToManyField(blank=True, to='hotel.habitacion'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='paquetes',
            field=models.ManyToManyField(blank=True, to='hotel.paquetepromocional'),
        ),
    ]
