# Generated by Django 4.2.5 on 2023-11-04 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0004_alter_alquiler_habitaciones_alter_alquiler_paquetes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Detalle_factura',
            new_name='DetalleFactura',
        ),
    ]
