# Generated by Django 4.2.5 on 2023-12-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_cliente_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_documento',
        ),
    ]
