# Generated by Django 4.2.5 on 2023-10-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_persona_cliente_encargado_vendedor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipohabitacion',
            name='precio',
        ),
    ]
