# Generated by Django 4.2.5 on 2023-10-21 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_tipohabitacion_precio'),
    ]

    operations = [
        migrations.AddField(
            model_name='encargado',
            name='encargado_asignado',
            field=models.BooleanField(default=False),
        ),
    ]
