# Generated by Django 4.2.5 on 2023-10-28 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_encargado_encargado_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encargado',
            old_name='encargado_asignado',
            new_name='asignado',
        ),
    ]
