# Generated by Django 4.2.5 on 2023-11-09 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_categoria_estrellas'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.direccion'),
        ),
        migrations.AddField(
            model_name='persona',
            name='correo',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AddField(
            model_name='persona',
            name='telefono',
            field=models.IntegerField(default=1),
        ),
    ]
