# Generated by Django 4.2.5 on 2023-11-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cliente_direccion_persona_correo_persona_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.direccion'),
        ),
    ]
