# Generated by Django 4.2.5 on 2023-11-10 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_persona_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
